config/routes.rb
Rails.application.routes.draw do
  # get 'bookmarks/index'
  # get 'bookmarks/new'
  # get 'bookmarks/create'

  # get 'bookmarks/show'
  # get 'movies/index'
  # get 'movies/show'
  # get 'movies/edit'
  # get 'movies/create'
  # get 'lists/index'
  # get 'lists/show'
  # get 'lists/edit'
  # get 'lists/create'
  root to: 'lists#index'
  resources :lists, only: %i[index new create show] do
    resources :bookmarks, only: %i[new create show]
  end
  resources :bookmarks, only: %i[destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length: { minimum: 6 }
  validates :movie, uniqueness: { scope: :list }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @list = List.find(params[:list_id])
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def show
    @bookmark = Bookmark.find(params[:id])
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy

    # no need for app/views/bookmarks/destroy.html.erb
    redirect_to list_path
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    @list.save
    # Will raise ActiveModel::ForbiddenAttributesError
    redirect_to list_path(@list)
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/destroy.html.erb
<h1>Bookmarks#destroy</h1>
<p>Find me in app/views/bookmarks/destroy.html.erb</p>

app/views/bookmarks/new.html.erb
<h1>new bookmark</h1>
<%=simple_form_for [@list, @bookmark] do |field|%>
<%=field.input :comment %>
<%=field.association :movie %>
<button class="m-2"><%=field.button :submit%></button>
<%end%>
<button class="m-2"> <%= link_to 'back', lists_path%> </button>

app/views/bookmarks/show.html.erb
<h1>Bookmarks#show</h1>
<h2><%= @bookmark.comment %></h2>
<p><%= @bookmark.list_id %></p>
<p><%= @bookmark.movie_id %></p>
<p> ----- <%= link_to 'bookmarking', new_list_bookmark_path(@bookmark)%> ---- </p>
<%= link_to 'back', list_path%>
<%= link_to "Delete #{@bookmark.comment}",
            bookmark_path(@bookmark),
            method: :delete,
            data: { confirm: "Are you sure?" } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<h1>lists</h1>

  <div class="row">
    <% @lists.each do |list| %>
       <div class="col-xs-12 col-sm-4">
          <div class="card">
            <%= list.name %>
            <p> ----------- </p>
            <%= "Category: #{list.name}"  %>
            <button class="m-2"><%= link_to 'details', list%></button>
          </div>
      </div>
    <% end %>
  </div>
  <hr>
  <div><p>Adding new lists</p></div>
  <hr>
  <button class="m-2"><p><%= link_to 'Add', new_list_path%> </p></button>

app/views/lists/new.html.erb
<h1>new lists</h1>
<%=simple_form_for(@list) do |field|%>
<%=field.input :name %>
<button class="m-2"><%=field.button :submit%></button>
<%end%>
<hr>
<button class="m-2"><%= link_to 'back', lists_path%> </button>

app/views/lists/show.html.erb
<h1>List: </h1>
<p>check al those movies out : </p>
<hr>
  <h1 class="m-2"><%= @list.name  %></h1>
  <div class="container">
      <div class="row">
            <% @list.bookmarks.each do |bookmark| %>
        <div class="col-6 d-flex">

          <div><% url = "https://image.tmdb.org/t/p/w1#{bookmark.movie.poster_url}"%>
            <%= image_tag url, alt:"poster", width: "300px" %>
          </div>
          <div class="px-2 ">
              <p><strong><%= bookmark.comment %></strong></p>
              <h4 class="card-title font-weight-bold"><%= bookmark.movie.title %></h4>
              <h6 class="card_text"><%= bookmark.movie.overview %></h6>
              <h6><strong><%= "Rating:"%></strong></h6>
              <h6><%= "#{bookmark.movie.rating}" %></h6>
              <%= link_to bookmark_path(bookmark), method: :delete, data: { confirm: "Are you sure?" } do %>
              <strong><i class="far fa-trash-alt" height= 100px></i></strong>
              <% end %>
          </div>
        </div>
          <% end %>
      </div>
  </div>
      <button class="m-4"><%= link_to 'Add Movie', new_list_bookmark_path(@list) %></button>
      <button class="m-2"><%= link_to 'Back', lists_path %></button>